### ISSUE TITLE
感谢学长细致的分享！询问有关初试排名问题。

### ISSUE THREAD

**Issue by tsingyawn** [FangmingZhou/ruc-cs#1]
请问学长，在去年复试名单公布前，各个考研群私下统计的初试成绩和最终公布的名单差距大吗？
谢谢学长~

**Comment by FangmingZhou** [comment]
我们去年是由学长拉了一个群，每个人进去备注改成自己的分数，有一份人没加群，有一部分人是乔装混进去看热闹的😅分数大部分人都是照实填的，也没有造假的必要吧
就是今年好像群挺多的?不知道大家有没有都填了?

**Comment by tsingyawn** [comment]
不是造假，是感觉今年填的人太少了，目前统计计算机学硕只有24个人填成绩，人工智能23个人填成绩，不知道是报的人少了还是有很多人漏填😅 都担心成绩不理想的话会不会收校外调剂了

**Comment by FangmingZhou** [comment]
如果分数不稳可以多做一手调剂的准备，如果是复试线上有24个cs学硕还是正常的
