### ISSUE TITLE
请问计算机类各专业之间可以相互调剂吗（计算机应用技术、大数据、信息安全、软件与理论）

### ISSUE THREAD

**Issue by tsingyawn** [FangmingZhou/ruc-cs#2]
是复试的时候计算机大类统一复试统一分配名额，还是分方向分配各个方向的名额呢？
谢谢学长

**Comment by FangmingZhou** [comment]
好像是统一名额的，我没有看到明文说明。但是往年都是统一的，所以也不存在专业之间的互相调剂

**Comment by tsingyawn** [comment]
谢谢学长的耐心回答！
请问复试的时候有要求带六级成绩单吗？

**Comment by FangmingZhou** [comment]
印象里应该是没有要求的
