### ISSUE TITLE
机试提问。。。

### ISSUE THREAD

**Issue by dzgdzgdzg** [FangmingZhou/ruc-cs#4]
学长，人大机试题目的中文英文啊？上机visual studio给不给用。。。打扰了

**Comment by FangmingZhou** [comment]
我们当时是中文的，机房的软件还是挺多，VS应该也是有的，我当时用的是dev

**Comment by dzgdzgdzg** [comment]
谢谢学长！！！

**Comment by DreamsofGg** [comment]
学长，你好，想问下机试题是类似于数据结构的算法还是动态规划之类的算法
