### ISSUE TITLE
导师推荐

### ISSUE THREAD

**Issue by moze-zhang** [FangmingZhou/ruc-cs#5]
学长好，我是22cs学硕的考生，成绩出来了，应该可以踩线进复试，是不是需要提前联系老师，个人喜欢计算机视觉，深度学习方向的，希望学长可以推荐几个老师!顺祝学长学习顺利，多发文章，感谢。

**Comment by FangmingZhou** [comment]
> 学长好，我是22cs学硕的考生，成绩出来了，应该可以踩线进复试，是不是需要提前联系老师，个人喜欢计算机视觉，深度学习方向的，希望学长可以推荐几个老师!顺祝学长学习顺利，多发文章，感谢。

导师需要尽早联系。
我们院做CV的老师很少，我了解的有：李锡荣，医疗图像方面；杨刚，同上；金琴，偏多媒体方向；刘桃，声音图像文字多模态；卢志武，跨模态对比学习，文生成图，视频自监督表示学习，压缩视频内容分析，图像语义分割；刘家俊。
你看一下他们近两年发的论文，就可以了解老师目前的方向了。
尽早联系
